### ISSUE TITLE
Images Do Not Send

### ISSUE THREAD

**Issue by NgXCyclone** [Yash094/memer-api#5]
**Describe the bug**
Images do not send anymore but worked fine before

**To Reproduce**
Use one of the API options

**Expected behavior**
Image of the meme to send

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/44649334/122609953-bd904880-d076-11eb-83c8-e0e0b2b2f587.png)

After
![image](https://user-images.githubusercontent.com/44649334/122609907-aa7d7880-d076-11eb-8049-acda4da6dead.png)

**Comment by ELITE-SMOKER-69** [comment]
Same Problem With Me Too

**Comment by Yash094** [comment]
Hello guys,
Memer-API had a huge update on 15 June and from then you need a token to use the API and any versions lower than 3.0.0 don't work anymore. 
You can get the token from our [support server](https://discord.com/invite/emD44ZJaSA)

**Comment by NgXCyclone** [comment]
ah ok, alright
